version: "3.5"
services:
  web-count:
    build: .
    command: python app.py
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  counter-vol: